version: '2.1'
# use existing network instead of creating solrcloud_default
networks:
  default:
    external:
      name: nat
services:
    sitecore:
        build: ./sitecore
        container_name: sitecore
        #image: mcr.microsoft.com/windows/servercore:ltsc2019
        hostname: sitecore-docker
        #domainname: sitecore-docker.local
        tty: true
        #stdin_open: true
        ports:
            - 8001:80
    zoo-1:
        image: zookeeper
        restart: always
        ports:
            - 2181:2181
        volumes:
            - ./data/zoo-1:/opt/persist
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
    solr-1:
        image: solr:7.2
        restart: always
        # lcow (linux containers on windows) ignores linux
        # users so it defaults to root hence using runuser
        # to explicitly set service user
        entrypoint: /bin/bash -c
        command: |
            "cd /opt/docker-solr/scripts/
            runuser solr -c \"docker-entrypoint.sh solr-foreground\""
        ports:
            - 8081:8081
        volumes:
            - ./data/solr-1/logs:/opt/logs
            - ./data/solr-1/store:/store
            - ./data/solr-1/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./data/solr-1/ssl-keys:/opt/ssl-keys
        environment:
            SOLR_SSL_KEY_STORE: /opt/ssl-keys/solr-ssl.keystore.jks
            SOLR_SSL_KEY_STORE_PASSWORD: secret
            SOLR_SSL_TRUST_STORE: /opt/ssl-keys/solr-ssl.keystore.jks
            SOLR_SSL_TRUST_STORE_PASSWORD: secret
            SOLR_SSL_NEED_CLIENT_AUTH: "false"
            SOLR_SSL_WANT_CLIENT_AUTH: "false"
            SOLR_SSL_KEY_STORE_TYPE: JKS
            SOLR_SSL_TRUST_STORE_TYPE: JKS
            SOLR_PORT: 8081
            SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181
            SOLR_LOGS_DIR: /opt/logs
            SOLR_HOST: solr-1
            SOLR_HEAP:
            SOLR_JAVA_MEM:
        depends_on:
          - zoo-1
